services:

#-------- frontend service---------------------------------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - internal

#--------Internal communication---------------------------------------------
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - "15672:15672"
    networks:
      - internal

volumes:
  db-auth-data:

networks:
  internal:
    driver: bridge