services:

  #-------- frontend services---------------------------------------------
  frontend:
    build:
      args:
        NODE_ENV: production
      target: production
    ports:
      - "80:80"

  #-------- backend services---------------------------------------------
  skripters-api-gateway:
    build:
      target: production
    environment:
      - SPRING_PROFILES_ACTIVE=production
    env_file:
      - .env.production

  skripters-auth:
    build:
      target: production
    environment:
      - SPRING_PROFILES_ACTIVE=production
    env_file:
      - .env.production