services:

#-------- backend services---------------------------------------------

  skripters-api-gateway:
    container_name: skripters-api-gateway-service
    build:
      context: ./services/skripters-api-gateway
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-development}
    ports:
      - "8080:8080"
    depends_on:
      - skripters-auth
      - rabbitmq
    networks:
      - internal

  skripters-auth:
    container_name: skripters-auth-service
    build:
      context: ./services/skripters-auth
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-development}
    ports:
      - "8081:8080"
    depends_on:
      - db-auth
      - rabbitmq
    networks:
      - internal
      - db-auth

  skripters-docs:
    container_name: skripters-docs-service
    build:
      context: ./services/skripters-docs
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-development}
    ports:
      - "8082:8080"
    depends_on:
      - rabbitmq
    networks:
      - internal
      - db-docs