services:

  #-------- frontend services---------------------------------------------
  frontend:
    image: jurajplayercze/frontend:latest
    ports:
      - "80:80"

  #-------- backend services---------------------------------------------
  skripters-api-gateway:
    image: jurajplayercze/skripters-api-gateway:latest
    environment:
      - SPRING_PROFILES_ACTIVE=production
    env_file:
      - .env.production

  skripters-auth:
    image: jurajplayercze/skripters-auth:latest
    environment:
      - SPRING_PROFILES_ACTIVE=production
    env_file:
      - .env.production

  skripters-docs:
    image: jurajplayercze/skripters-docs:latest
    environment:
      - SPRING_PROFILES_ACTIVE=production
    env_file:
      - .env.production