services:
#-------- frontend services---------------------------------------------
  frontend:
    build:
      args:
        NODE_ENV: development
      target: development
    ports: 
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

#-------- backend services---------------------------------------------
  skripters-api-gateway:
    build:
      target: development
    environment:
      SPRING_PROFILES_ACTIVE: development
    env_file:
      - .env.development
    volumes:
      - ./services/skripters-api-gateway:/app

  skripters-auth:
    build:
      target: development
    environment:
      SPRING_PROFILES_ACTIVE: development
    ports:
      - "8081:8080"
    env_file:
      - .env.development
    volumes:
      - ./services/skripters-auth:/app

  skripters-docs:
    build:
      target: development
    environment:
      SPRING_PROFILES_ACTIVE: development
    ports:
      - "8082:8080"
    env_file:
      - .env.development
    volumes:
      - ./services/skripters-docs:/app


#-------- databases---------------------------------------------
  db-auth:
    ports:
      - 5432:5432
    volumes:
      - db-auth-data:/var/lib/postgresql/data
  db-docs:
    ports:
      - 5433:5432
    volumes:
      - db-docs-data:/var/lib/postgresql/data