services:

  #-------- frontend services---------------------------------------------
  frontend:
    build:
      args:
        NODE_ENV: development

  #-------- backend services---------------------------------------------
  skripters_api_gateway:
    env_file:
      - .env.development

  skripters_auth:
    env_file:
      - .env.development
