spring:
  devtools:
    restart:
      enabled: true
    live-reload:
      enabled: true

  datasource:
    url: jdbc:postgresql://db-docs:5432/${DOCS_POSTGRES_DB}
    driver-class-name: org.postgresql.Driver
    username: ${DOCS_POSTGRES_USER}
    password: ${DOCS_POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect