spring:
  datasource:
    url: jdbc:postgresql://db-docs:5432/${DOCS_POSTGRES_DB}
    driver-class-name: org.postgresql.Driver
    username: ${DOCS_POSTGRES_USER}
    password: ${DOCS_POSTGRES_PASSWORD}

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      connection-timeout: 30000
      leak-detection-threshold: 2000



  jpa:
    open-in-view: false