spring:
  profiles:
    active:
      - ${SPRING_PROFILES_ACTIVE:development}

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: "http://skripters-auth-service:8080"
          predicates:
            - Path=/auth/**

        - id: docs-service
          uri: "http://skripters-docs-service:8080"
          predicates:
            - Path=/tiles/**