#!/bin/bash

VERSION="1.0.0"

source "$(dirname "${BASH_SOURCE[0]}")/scripts/functions/log.sh"

cmd::version() {
    local env=$1
    log::info "Skripters Manager"
    log::info "Version: $(get_version)"
    log::info "Environment: $env"
}

get_version() {
    echo "$VERSION"
}