name: CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [frontend, services/api-gateway, services/auth, services/docs ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest ./backend/${{ matrix.service }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest