name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [frontend, skripters-api-gateway, skripters-auth, skripters-docs]
        context-path: ['./frontend', './services/skripters-api-gateway', './services/skripters-auth', './services/skripters-docs']
        target-stage: ['production', 'production', 'production', 'production']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push image
      run: |
        docker build \
          --target ${{ matrix.target-stage }} \
          -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest \
          ${{ matrix.context-path }}
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest
