name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
  pull_request:
    branches:
      - main
      - develop


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [frontend, services/skripters-api-gateway, services/skripters-auth, services/skripters-docs ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build ${{ matrix.service }}
      working-directory: ./${{ matrix.service }}
      run: mvn clean verify -B