name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, services/skripters-api-gateway, services/skripters-auth, services/skripters-docs ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up environment and build
      run: |
        if [[ "${{ matrix.service }}" == "frontend" ]]; then
          echo "Building frontend with Node.js"
          cd frontend
          npm install
          npm run build
          npm test
        else
          echo "Building Java service ${{ matrix.service }}"
          cd ${{ matrix.service }}
          mvn clean verify -B
        fi